### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by bkaradzic** [jpcy/ioq3-renderer-bgfx#1]
This is cool! :+1: 

I would like to link this project on "Who is using it?" section on main bgfx page: https://github.com/bkaradzic/bgfx#who-is-using-it, but I need screenshot. Ideally one that shows bgfx stats, since I assume it looks identical to default GL renderer from ioquake3. :)

Thanks!

**Comment by jpcy** [comment]
![](http://i.imgur.com/d6OhVYK.jpg)

No dynamic lighting or gamma correction yet, but otherwise it looks the same as the GL1 renderer.

Great job with bgfx. The API is so much nicer than using GL or D3D directly.

**Comment by bkaradzic** [comment]
Thanks! I updated README. :+1:
