### ISSUE TITLE
BGFX Texture2D

### ISSUE THREAD

**Issue by travmon** [jpcy/ioq3-renderer-bgfx#7]
Testing this renderer with UrbanTerror.  tested precompiled, and my own compile, getting crash with a few weapons. Can work around by not showing weaps with `cg_drawhands` Maybe some bgfx recent updates resolved this? `tty]../code/bgfx/src/renderer_gl.cpp (4826): BGFX Texture2D   744: RGBA8 (requested: RGBA8), layers 1, 256x256x0.` 
![shot0008](https://user-images.githubusercontent.com/1417786/54868667-baaa2e80-4d6d-11e9-846d-3106d8d21662.jpg)

**Comment by travmon** [comment]
![shot0026](https://user-images.githubusercontent.com/1417786/54869944-83904900-4d7e-11e9-8fc1-97d3286bc5cc.jpg)

**Comment by jpcy** [comment]
I couldn't reproduce this, but I updated bgfx, so try the latest build. I also fixed overbrightening in urt.
