### ISSUE TITLE
Lightning gun effect is just a very narrow line

### ISSUE THREAD

**Issue by Axonimpulse** [jpcy/ioq3-renderer-bgfx#8]
I'm enjoying the extra dynamic lights very much. 
However there's something very strange with how the LG effect is rendered. 
It's just a very narrow line now. Any idea what may be wrong ? 
Thank you !

**Comment by jpcy** [comment]
If you're using a low value for r_railCoreWidth (default is 6), that should be fixed now.

**Comment by Axonimpulse** [comment]
Thank you very much, it works perfectly now with your latest version !

I absolutely love what you have achieved ! These changes, especially the
extra dynamic lights make a lot of difference to how the game feels !

If you are interested to add more features, a particle system for the
explosions would be wonderful.

I wish you a nice week-end !
