### ISSUE TITLE
It seems that Autosprite case not processed in setDeformUniforms method

### ISSUE THREAD

**Issue by suijingfeng** [jpcy/ioq3-renderer-bgfx#9]
Hello, thank you for this nice project ! I test your excellent render on openarena game, which very similar to quake 3 arena but still have small difference in shader material construction.  My problem is that the rocket explosion visual effect not rendered correctly.  I attached a picture
to illustrate the case: 

![rocket_explosion_not_correctly](https://user-images.githubusercontent.com/10341056/59980497-6000c700-9629-11e9-880e-a1fad7ccb475.jpg)

After debugging a while, I find that it may caused by `animmap` not handled correctly.
```
rocketExplosion
{
	{
		animmap 8 models/weaphits/rlboom/rlboom_1.tga models/weaphits/rlboom/rlboom_2.tga models/weaphits/rlboom/rlboom_3.tga models/weaphits/rlboom/rlboom_4.tga models/weaphits/rlboom/rlboom_5.tga models/weaphits/rlboom/rlboom_6.tga models/weaphits/rlboom/rlboom_7.tga models/weaphits/rlboom/rlboom_8.tga 
		blendfunc gl_one gl_src_alpha
		rgbGen wave inversesawtooth 0 1 0 8 
	}
	{
		animmap 8 models/weaphits/rlboom/rlboom_2.tga models/weaphits/rlboom/rlboom_3.tga models/weaphits/rlboom/rlboom_4.tga models/weaphits/rlboom/rlboom_5.tga models/weaphits/rlboom/rlboom_6.tga models/weaphits/rlboom/rlboom_7.tga models/weaphits/rlboom/rlboom_8.tga models/weaphits/rlboom/rlboom_8.tga 
		blendfunc gl_one gl_src_alpha
		rgbGen wave sawtooth 0 1 0 8 
	}
	{
		clampmap textures/oa/fiar.tga
		blendfunc add
		rgbGen wave inversesawtooth 0.1 0.8 0 1 
		tcMod rotate 77
		tcMod stretch inversesawtooth 0.1 1 0 0.4 
	}
	{
		clampmap textures/oa/fiar2.tga
		blendfunc add
		rgbGen wave inversesawtooth 0 1 0 1 
		tcMod rotate 33
		tcMod stretch sin 0.2 1 0 0.4 
	}
	{
		clampmap textures/oa/fiar.tga
		blendfunc add
		rgbGen wave sin 0 1 0 1 
		tcMod rotate -17
		tcMod stretch sawtooth 0.1 1.5 0 1
	}
	{
		clampmap textures/oa/fiar.tga
		blendfunc add
		rgbGen wave inversesawtooth 0.1 1 0 1
		tcMod rotate -77
		tcMod stretch sawtooth 0.4 0.8 0 1 
	}
}
```
I have no idea how to handle this as i am not  familiar with bgfx, so I decide report to you.

**Comment by jpcy** [comment]
Looks like a problem with soft sprites. See if setting `r_softSprites` to 0 fixes it.

**Comment by suijingfeng** [comment]
The black bar(stump?) do not showing on some map by setting r_softSprites to 0  on some maps, issues still exits on other maps :( , the flares on the tail of the rocket still not render correctly. as the following pictures shows:

* normal:
![rocketFlare](https://user-images.githubusercontent.com/10341056/60022941-63e32680-96c7-11e9-8af8-97652148a548.jpg)

* without rocket flare: 
![rocketwithoutFlare](https://user-images.githubusercontent.com/10341056/60023736-fdf79e80-96c8-11e9-94bb-76aa1e63bb8b.jpg)

* normal:
![powerUp_correct](https://user-images.githubusercontent.com/10341056/60023835-34351e00-96c9-11e9-922c-721b3c2e63cb.jpg)

* power-up flare not rendered: 
![powerUp_wrong](https://user-images.githubusercontent.com/10341056/60023891-50d15600-96c9-11e9-919b-a52a9ccc7fb6.jpg)

* normal ui
![ui_correct](https://user-images.githubusercontent.com/10341056/60024005-8a09c600-96c9-11e9-8fca-200670b83190.jpg)
*  shining flare at background disappear 
![ui_wrong](https://user-images.githubusercontent.com/10341056/60024092-bf161880-96c9-11e9-864a-c8bd0fb2ad18.jpg)

Normally those effect are rendered by AutospriteDeform() function,  when i comment this function in rendergl2 module,  then those flares disappear as you render module does.

**Comment by jpcy** [comment]
The first problem was caused by `blendfunc gl_one gl_src_alpha`, which is the same as additive blend if alpha is 1, but scales dest color, so soft sprites where rendering as black where the softening effect kicks in as alpha value approached 0.

I can't get OA to build on windows to debug the other problems. I suspect there are local changes to the renderers in OA that change behavior. Autosprite deforms work fine in ioquake3 (handled [here](https://github.com/jpcy/ioq3-renderer-bgfx/blob/master/code/renderer_bgfx/Material_calculate.cpp#L600)).

**Comment by suijingfeng** [comment]
Thanks to you.
